version = 1

[[annotations]]
path = [
    "requirements/**.txt",
    "requirements/**.in",
    ".basedpyright/baseline.json",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "Unlicense"

[[annotations]]
path = ["typings/libdnf5/*.pyi", "typings/rpm/*.pyi"]
precedence = "override"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "Unlicense"
